services:
  streamlit:
    build: .
    container_name: cours-streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      # Supabase – stockées dans ton fichier .env (monté automatiquement)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    env_file:
      - .env